import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="p-8 text-right text-lg">
          <div className="font-bold">
            <a href="#" className="mr-4 inline tracking-tighter">
              HOME
            </a>
            <a href="#issues" className="dropdown mr-2 inline">
              THE ISSUES
            </a>

            <a href="#about" className="mr-4 inline tracking-tighter">
              ABOUT
            </a>
            <a href="#contact" className="mr-4 inline tracking-tighter">
              CONTACT
            </a>
          </div>
        </nav>
        {children}
        <footer className="place-self-center mt-24 mb-10 border-[1px] border-white p-1 tracking-tighter text-sm">
          <p>PAID FOR BY ANSONIA DTC, JAMES MALLOY, TREASURER</p>
        </footer>
      </body>
    </html>
  );
}

{
  /*
  
  <div>
              <div className="dropdown-content">
                <a href="#city-financials">City Financials</a>
                <a href="#city-scandals">City Scandals</a>
                <a href="#wpca-sale">The WPCA Sale</a>
                <a href="#personal-scandals">Personal Scandals</a>
              </div>
            </div>

  */
}
